### PR TITLE
Add v16.x docs

### PR DESCRIPTION
**Pull request by JohnTitor**
Add v16.x docs as Active LTS will start soon.

### CODE REVIEW

**Comment by JohnTitor** [comment]
How do we generate locales dirs? I'm not sure why the test complains only about v16.x, not v14.x.

**Comment by TiagoDanin** [comment]
> How do we generate locales dirs?

Is generated by Crowdin Bot

> I'm not sure why the test complains only about v16.x, not v14.x.

The test "accepts arguments for nodeVersion and locale" previously checked the version `v13.x` your folder has the `es-ES` but the `supportedVersions[1]` ([ref](https://github.com/nodejs/i18n/blob/8bb3d7e3cf6afd1fb267f6a4635d6e512232f2f4/test.js#L105)) now returns `v14.x` that's a problem because he doesn't have the folder `es-ES`.

Recommend replace the test: 

https://github.com/nodejs/i18n/blob/8bb3d7e3cf6afd1fb267f6a4635d6e512232f2f4/test.js#L104-L114
`supportedVersions[1]` -> `supportedVersions[2]`

**Comment by JohnTitor** [comment]
Thanks for the pointer :) Updated the test as suggested.

**Review by TiagoDanin — APPROVED** [review]
LGTM 💯

**Pull request merged**
