### PR TITLE
build: Only lint when JS files are touched

### PR DESCRIPTION
**Pull request by nschonni**
Also include the package.json files in case they change the results

### CODE REVIEW

**Comment by maddhruv** [comment]
@nschonni why are we removing `lint` from the checks github action? standard is a very lightweight tool around eslint and shall run on `.js` files only and doesn't take much time linting. Separate both checks (test & lint) will take more time (I think) and resources - installing the dependencies again, waiting for check status to update in the PR, while both of them serve the same intention here - check if the PR is correct/error-free here or not.

**Comment by nschonni** [comment]
These runs should be executed in parallel if JS files are touched. In PRs with MD only changes any errors that linting raises would be false positives.

Aside, the Standard ESLint rules aren't what NodeJS uses, but currently they're an embedded config in the repo, so it's not easy to adopt here.

**Comment by maddhruv** [comment]
Cool LGTM

**Comment by nschonni** [comment]
Rebased for the new dependency bumps, and fixed a new lint issue

**Pull request merged**
