### PR TITLE
Remove unneeded files

### PR DESCRIPTION
**Pull request by JohnTitor**
We no longer have to sync content here, and removed related packages.

### CODE REVIEW

**Comment by AugustinMauroy** [comment]
I think it's a good idea.

**Review by AugustinMauroy — CHANGES_REQUESTED** [review]
I block to let the time to next-10 (that to a project of I18N the docs) to look to this pr.

**Comment by nschonni** [comment]
@AugustinMauroy why did you block the PR and then remove all the prevously translated content? Removing the translated content wasn't what this PR was proposing. Please don't push unrelated changes into someone elses PR

**Comment by AugustinMauroy** [comment]
They are no translated content on this repo.

**Comment by AugustinMauroy** [comment]
> why did you block the PR

Because we remove a piece of code that can be used in the reflection

**Comment by nschonni** [comment]
> They are no translated content on this repo.

Incorrect, this repo has been used to translate the API docs with Crowdin long before the website onboarded

**Comment by AugustinMauroy** [comment]
And translation stay on Crowdin. Just remove from here. Also if we remove the script for uploading and downloading. This content will become out of date.

**Comment by nschonni** [comment]
@AugustinMauroy I get that you're eager to help, but this isn't correct. Generally in OSS it's bad etique to push changes to other peoples branches without discussing. If you think removing the content is the right thing, you can open your own PR and describe why you thing this is right, rather than highjacking someone else's PR.
This PR was opened to stop additional sync PRs for the active branches only. You're suggesting wiping out the translation history

**Review by AugustinMauroy — APPROVED** [review]
LGTM

**Comment by JohnTitor** [comment]
@nodejs/i18n Could anyone tweak the "Require status checks to pass before merging" config on the branch protection rule?

**Comment by TiagoDanin** [comment]
> @nodejs/i18n Could anyone tweak the "Require status checks to pass before merging" config on the branch protection rule?

I will close and reopen the pull request. Hope this fixes it

**Comment by JohnTitor** [comment]
> I will close and reopen the pull request. Hope this fixes it

No, it won't. The repo config needs to be tweaked as mentioned.

**Review by Trott — APPROVED** [review]

**Pull request merged**
