### PR TITLE
Hi, I would like to join the group

### PR DESCRIPTION
**Pull request by lxmarinkovic**
Hi @JohnTitor, I would like to join the group and contribute as well 🚀

### CODE REVIEW

**Comment by JohnTitor** [comment]
Unfortunately, I don't have the access to Node.js org or Crowdin to invite you, while I could merge this PR, so I actually cannot let you join the WG, sorry.

**Comment by aduh95** [comment]
@nodejs/i18n

**Review by srl295 — APPROVED** [review]

**Comment by lxmarinkovic** [comment]
Hi again,

If you are able it would be nice to merge this pr as I already have
access to crowdin

**Comment by AugustinMauroy** [comment]
> Hi again, If you are able it would be nice to merge this pr as I already have access to crowdin


I don't have the ability to get you in but if you apply you will be accepted. (that's what I did)

**Comment by lxmarinkovic** [comment]
Hi @AugustinMauroy , thanks for the tip, but I am unsure where/how to apply. Can you give me a direction 🤔 I am, e.g., a member of JavascriptLandia, but I suppose you haven't thought about that. So if possible, please tell me how did you apply 😀

**Comment by AugustinMauroy** [comment]
@lxmarinkovic I just gave my @ and GitHub and said I like nodejs i18n member

**Comment by lxmarinkovic** [comment]
Cool, thank you @AugustinMauroy 😃

**Comment by AugustinMauroy** [comment]
Hey @lxmarinkovic! Are you an Crowdin ?
We stop translating with pr so the I18n teams are dissolved.

**Comment by lxmarinkovic** [comment]
> Hey @lxmarinkovic! Are you an Crowdin ? We stop translating with pr so the I18n teams are dissolved.

Hi @AugustinMauroy , thank you for asking! Yes, I am on nodejs-crowdin 👍

**Pull request closed without merging**
