### PR TITLE
Add @srl295

### PR DESCRIPTION
**Pull request by srl295**
Fixes: https://github.com/nodejs/i18n/issues/12

### CODE REVIEW

**Comment by srl295** [comment]
https://github.com/nodejs/i18n/blob/master/README.md#summary-of-our-responsibilities was not mentioned in the original commit ,so I missed it.  I'm:
* ex-moderator of ex-WG (now Team) `Intl`
* work on CLDR/ICU etc
* attending the Ecma 402 WG call tomorrow (I'll represent i18n if you want!)

do we want to have any kind of liaison relationships here? Maybe I can help there?

**Comment by obensource** [comment]
I'm really excited to have you with us @srl295–I truly appreciate your work, and am excited to add to it and connect along the way here in the i18n WG! 🙌

Concerning having a liaison to the Ecma 402 group–yes please! I would love to talk with you more about that over time and have you represent the i18n initiative there. Even more, I personally would be thrilled to join you next time as an observer and learn along the way! 🙌

I think the overlap of what you've been working on for some time with CLDR/ICU, Intl, the 402 WG, and everything else can really strengthen our perspective here and help make this group successful for what we have ahead of us. Thank you so much for wanting to jump in as a member, can't wait to talk more! 🍻

**Comment by obensource** [comment]
@srl295 would you mind updating your PR to reflect the recent alphabetization of the group members list that landed in #11? Thanks so much! 🙌

**Comment by srl295** [comment]
@obensource mutual! I'm glad that i18n is in scope of this group.

**Pull request merged**
