### PR TITLE
Add member Sam Yamashita

### PR DESCRIPTION
**Pull request by obensource**
Adding Sam Yamashita to our current members list.

### CODE REVIEW

**Comment by rachelnicole** [comment]
+1 from me too!!

**Comment by obensource** [comment]
@bnb I think we still need to add folks as collaborators of this repo to give them access. Can you verify that everyone on our [current members list](https://github.com/nodejs/i18n#current-members) has been added, and I'll ping you when we need to add new members? (I don't have those permissions) Thanks a bunch! 🙌

**Comment by bnb** [comment]
@obensource I just added this repository as a repo under @nodejs/i18n. Every member should (?) now have write access.

**Comment by obensource** [comment]
@bnb perfect. Thanks! 🎉🎉🎉

**Pull request merged**
