### PR TITLE
Add Jonathan Cardoso as member

### PR DESCRIPTION
**Pull request by JCMais**

### CODE REVIEW

**Comment by sotayamashita** [comment]
@JCMais I think this list will be ordered alphanumerically. Please change

**Comment by JCMais** [comment]
I was in doubt about that, will change it.

**Comment by JCMais** [comment]
I've fixed the ordering and added my name to it

**Comment by sotayamashita** [comment]
cc:/ @bnb

**Comment by bnb** [comment]
@sotayamashita I'm not actually a member 😬 

@obensource is leading the charge on this. I know he's super busy with some other things right now, so hang tight ❤️

**Comment by obensource** [comment]
@sotayamashita @JCMais @bnb thanks for your patience everyone. We're going to get a doodle out to everyone tomorrow to set up our next WG meeting. Excited to see y'all there!

**Comment by obensource** [comment]
Thanks for making the list alphanumerical.

**Comment by obensource** [comment]
@JCMais please pull the latest and adjust. Thanks a bunch! 🍻

**Comment by sotayamashita** [comment]
ref: #9

**Comment by JCMais** [comment]
@obensource I've rebased the PR to include @rajzshkr name from their PR.

**Pull request merged**
