### PR TITLE
Add glossary

### LINKED ISSUE #81: Create Crowdin Glossary
Crowdin has a glossary feature that presents translators with useful information about the terms they're translating (or should not be translating). Here's an example:

36569408-8a4ad454-17e2-11e8-8a5b-9c394db0eafd

For nodejs/i18n, we should probably start with the following:

- node module names: `fs`, `path`, `net`, etc
- JavaScript builtins like `Array`, `Boolean`, etc. We can use the [builtins](https://ghub.io/builtins) module for this.

I've extracted our Crowdin glossary code from electron/i18n and created a new node module [crowdin-glossary](https://ghub.io/crowdin-glossary) that we can use:

```js
const glossary = require('crowdin-glossary')({
  project: 'nodejs'
})

Object.keys(globals.builtin).forEach(term => {
  glossary.add(term, 'This is a JavaScript builtin and should usually not be translated.')
})
 
glossary.upload()
```

For more info on Electron's glossaries, see https://github.com/electron/i18n/blob/master/contributing.md#glossaries

### PR DESCRIPTION
**Pull request by maddhruv**
Contains:
- Generally used NF terms
- Node core terms
- General Programming/JS terms

These are some of the terms I found, feel free to modify.

**NOTE: Syntax of JSON file as per the `crowdin-glossary` `.fromFile()` function**

Resolves #81

### CODE REVIEW

**Comment by maddhruv** [comment]
added `do-not-merge`
wait until we build a sufficient glossary covering almost all possible terms.
have to read the whole docs again, I guess :stuck_out_tongue_closed_eyes:

**Comment by maddhruv** [comment]
@zeke
Please have a look at it

**Comment by ryo-a** [comment]
I think `callbacks` also can be translated.

**Comment by laosb** [comment]
Actually I'm thinking words and phrases like "Foundation", "Board of Directors", full expressions of committee names *should* be translated for better understanding.

**Comment by maddhruv** [comment]
> Actually I'm thinking words and phrases like "Foundation", "Board of Directors", full expressions of committee names should be translated for better understanding.
@laosb actually these words have a meaningful translation to the respective languages which would somehow change the real meaning for them

e.g: `Node.js Foundation` in Hindi would be `node.js नींव` -> `node.js foundation` | `node.js groundwork` | `node.js base`

that we shall not expect here I guess

**Comment by laosb** [comment]
Actually listing all those terms in a “don’t-translate” list would cause the sentence being too noisy and uneasy for non-native speakers. It might looks fine for those who could understand English words, but a disaster for those who don’t understand. Long unpronounceable and nonsense English phrases make a reader quickly sleepy, and extra explanations would be needed for those phrases, which can be self-explaining if they are properly translated.

**Comment by zeke** [comment]
> e.g: `Node.js Foundation` in Hindi would be `node.js नींव` -> `node.js foundation` | `node.js groundwork` | `node.js base`

Great point. But instead of just adding "do not translate" in the glossary, we should say something like "The Node.js Foundation is the institution that manages the Node.js project". This will give translators the context they need to translate the word using the appropriate sense.

**Comment by RichardLitt** [comment]
> Wait until we build a sufficient glossary covering almost all possible terms.

I think we should probably merge this is and use it, as opposed to the current long-open PR. Then, we can iterate. So - mind if we remove `do-not-merge` and merge this?

**Comment by maddhruv** [comment]
Thanks @RichardLitt for the update, +1 from my end

**Pull request merged**
