### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by nodejs-crowdin**
Enjoy!

### CODE REVIEW

**Comment by lukaszewczak** [comment]
Wow, this is realy big PR, what steps should be taken now, should we review it, somehow - what we shoul look for?

**Comment by JCMais** [comment]
My inbox just got full, lol

**Comment by maddhruv** [comment]
:heart: :heart: 
we are getting healthy and fresh fruits :kiwi_fruit: :cherries: :strawberry: down here.

Good work @zeke @obensource @Andrulko and everyone else

**Comment by zeke** [comment]
@lukaszewczak this is the very first PR from Crowdin, so it's backfilling all ~30 languages with default (English) content. It should be safe to merge it at any time, but I would prefer to let it sit for a bit until the build stabilizes and CI is passing. We should also add some more tests now that we have translated content. I opened https://github.com/nodejs/i18n/issues/101 for that.

**Comment by zeke** [comment]
I belive we are seeing all those ❌ because Travis automatically cancels running builds when new commits are added to the pull request.

**Comment by zeke** [comment]
The initial sync is complete and this is now ready to land!

Anyone in @nodejs/i18n can feel free to approve and merge.

**Comment by zeke** [comment]
The initial Crowdin sync is complete and this is ready to go. Anyone in @nodejs/i18n should feel free to approve and merge.

**Comment by zeke** [comment]
> I have just enabled auto cancellation of builds for old commits on PRs at Travis

Thank you, @JCMais 👍

**Pull request merged**
