### PR TITLE
fetch releases from GitHub Releases

### PR DESCRIPTION
**Pull request by maddhruv**
Would be useful in fetching releases and figuring out which all versions being added to the repo content as well as skip already fetched content

### CODE REVIEW

**Comment by zeke** [comment]
Nice!

@MylesBorins can the GitHub Releases data be used as a source of truth to determine latest Node.js version numbers (assuming we filter out prereleases and drafts)?

@maddhruv if this is to become our source of truth, do you wanna take this a step further and make this process also update the `nodeVersions` object in package.json? If so, we'll need to use the `semver` module to figure those out. Something like `semver.maxSatisfying(versions, range)` where versions is an array of version numbers (maybe without the `v` prefix?) and range is something like `10.x`.

**Comment by lukaszewczak** [comment]
Nice! But this script will not work on my Windows machine :-(

**Comment by MylesBorins** [comment]
The changelog is a better source of Truth. We update the website as soon as
doing the release but sometimes forget to add release notes to GitHub
release

**Comment by zeke** [comment]
> The changelog is a better source of Truth

What if we are only interested in version numbers (not release notes)? Also what changelog are you referring to?

> this script will not work on my Windows machine

Thanks for pointing that out. Rather than using `curl` and pipes, let's move this into a JS file that figures out latest versions and updates package.json. We also don't really need to write the release data to disk. We just need the latest version number.

**Comment by maddhruv** [comment]
> process also update the nodeVersions object in package.json

we can put metadata inside the `content` dir keeping track of the latest version we have fetched into the dir so that we wont download it back again and also help us decide which remains

**Comment by alexandrtovmach** [comment]
@zeke @maddhruv Does it something still useful?

**Comment by zeke** [comment]
I'm not sure what the state of this is. Looks like this is related: https://github.com/nodejs/i18n/issues/246

**Comment by alexandrtovmach** [comment]
Closed in favor of #281

**Pull request closed without merging**
