### PR TITLE
request to join nodejs i18n team

### PR DESCRIPTION
**Pull request by amor520**
add member Amor

### CODE REVIEW

**Comment by amor520** [comment]
#43

**Comment by maddhruv** [comment]
I don't know why adding the name at the top? :thinking:

**Comment by amor520** [comment]
@maddhruv I thought it was arranged alphabetically ~ ~

**Comment by RichardLitt** [comment]
Unfortunately this now needs a rebase! But I support your addition. :) Can you tell us a bit more about yourself and why you want to be on this committee?

**Comment by amor520** [comment]
@RichardLitt 
 I'm currently member of the electron/i18n team, use nodejs，go，python at work. I think joining the community, doing translations, etc. will allow me to learn more and enjoy programming more easily.

**Comment by RichardLitt** [comment]
Sweet! Thanks for that. After the rebase, I think this is good to go.

**Comment by amor520** [comment]
thanks!

**Comment by obensource** [comment]
@amor520 So stoked you're joining us! Excited to have you. 🍻

Would you please update your PR to reflect the current members list table which was added recently? Thanks so much! 🙌

**Comment by amor520** [comment]
close this pull request, see #47

**Comment by obensource** [comment]
Thank you @amor520! 🍻

**Pull request closed without merging**
