### PR TITLE
feat: Bump to Node 12.16.2  and 10.20.0

### PR DESCRIPTION
**Pull request by nschonni**
Content will be synced by nightly job afterwards

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
But why not this way #281?

**Comment by nschonni** [comment]
@alexandrtovmach simliar approach was offered in #113 and was never merged. This gets the content to be updated while that other PR is being discussed

**Comment by alexandrtovmach** [comment]
@nschonni Truth, but now I'm here forcing active development, and we wouldn't have staled things until I'm here (sounds so naive and ambitious 😄 )

I'd like to please you to review and probably approve #281 instead of doing manual stuff, I really appreciate it =)

**Comment by alexandrtovmach** [comment]
And yeah, about #113:
It wasn't ideal solution (too simply and not universal), and unfortunately staled for no reason

**Comment by alexandrtovmach** [comment]
Closed in favor #281

**Pull request closed without merging**
