### PR TITLE
[WIP] Add minutes of Apr 10.

### PR DESCRIPTION
**Pull request by laosb**
Because of incomplete note taking, this is just a copy-over from Google Docs original file with some Markdown styling adjustments. IMO this can be completed if everyone could recall some details.

### CODE REVIEW

**Comment by maddhruv** [comment]
The minute contains very little of the conversations! :confused:

**Comment by zeke** [comment]
It would be cool if we could record these meetings and use a transcription service to get a text version of the conversation.

**Comment by maddhruv** [comment]
Do you know some of them?

**Comment by ryo-a** [comment]
YouTube can generate (downloadable) captions.
It works on not only public but also limited access videos.
https://support.google.com/youtube/answer/100078?co=GENIE.Platform%3DDesktop&hl=en-GB

it's worth trying.

**Comment by lukaszewczak** [comment]
At the end of the meeting, @zeke pointed to the translation problem for many node.js versions, Andriy mentioned that he would potentially have several possible solutions to this problem and could present them at the next meeting.

By the way, I want to ask if you know how creating notes from meetings in other groups looks like, is there one person delegated to this?

**Comment by laosb** [comment]
Sounds like time for another meeting, and we don't have this meeting note ready yet. Next time we may just use some kind of voice2text software with little human efforts?

**Comment by RichardLitt** [comment]
I think we can fix this process by nominating a secretary to take notes, and by using a collaborative note software. The secretary can be a shared position with multiple members, or rotate; and they'd be in charge of getting this done. I don't think that voice2text is at the point yet where it would work. I also don't think the problem is the tools, but the process.

**Comment by zeke** [comment]
We use http://hackmd.io/ on the Electron team calls for collaborative note-taking. Works pretty well. Would hackmd again.

**Pull request merged**
