### PR TITLE
Remove MIT license until further discussion is held

### PR DESCRIPTION
**Pull request by obensource**
## Purpose
I [committed](https://github.com/nodejs/i18n/pull/23) the MIT license to our WG repo after yesterday's CommComm discussion, but I believe that was a premature action. 'Adding an appropriate license to a non-code repository' is a conversation in our greater community that is [still in process](https://github.com/nodejs/community-committee/issues/245#issuecomment-367909223). We should wait on this, and continue our discussion regarding it with CommComm in their related issue (whenever it exists).

## Description
This commit provides a simple removal of the MIT license from our repo, rather than a revision of our history.

## Context
@RichardLitt provided some sane context around this issue in our [recent conversation](https://github.com/nodejs/i18n/pull/23#issuecomment-367860586).

### CODE REVIEW

**Comment by RichardLitt** [comment]
LGTM. This makes sense. Thanks, @obensource!

**Comment by bnb** [comment]
This should be able to be merged 👍

**Comment by RichardLitt** [comment]
Thanks all!

**Comment by obensource** [comment]
Thanks @bnb & @RichardLitt! 🙌

**Pull request merged**
