### PR TITLE
refactor: Removed old meeting minutes

### PR DESCRIPTION
**Pull request by alexandrtovmach**

### CODE REVIEW

**Comment by nschonni** [comment]
Can you split this up? Your suggesting 2 separate things here:
1. Removing the status script. Think this was copied over from the electron setup, and there are probably some other changes like the .gitignore needed https://github.com/nodejs/i18n/blob/93e709e9717d701e80fdb93b86a24c73a9fe01d2/.gitignore#L9
2. Removing old meeting minutes. Not sure why this would be wanted

**Comment by alexandrtovmach** [comment]
@nschonni Probably you right, it's better to split this changes, but in general it's both refactor stuff

**Comment by alexandrtovmach** [comment]
Updated PR to remove `minutes/` folder. I'd like to remove it, because it seems redundant and some history artifacts that will never use

**Comment by alexandrtovmach** [comment]
Split up a part of changes to separate PR #284 . Thanks @nschonni for this https://github.com/nodejs/i18n/pull/268#issuecomment-612175392

**Pull request merged**
