### PR TITLE
docs: Added all versions content

### PR DESCRIPTION
**Pull request by alexandrtovmach**
- pulled by script content for all versions
- updated tests to require supported versions and not limit with
- TEMPORARY turned off npm module tests, until get translations for that 

related: #310

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
> Test Code shouldn't be commented out to disable it

This is edge case when we haven't translations for version, and this never going to happen in a future

**Comment by alexandrtovmach** [comment]
> the commits that deleted the files should be reverted to return the previous translations

Agree with you, but it's a bit complicated to cherrypick stuff, instead of just grab new content

**Comment by alexandrtovmach** [comment]
@zeke On prev meeting you asked me about Windows issues, and here we are 😄. Check [this commit](https://github.com/nodejs/i18n/pull/313/commits/08a0fbfa7dc2b638eab339946dfbb6c3a2ae8d27) for more details

@nschonni Thanks for pointing me with tests. Fixed and uncommented it 👍

**Comment by alexandrtovmach** [comment]
@nschonni About reverting commits - it havent sense, because we don't care anymore about commits history, and important for us is just to push and pull content from Crowdin. In a few months our commits history will become like this:

- New translations from Crowdin
- New translations from Crowdin
- New translations from Crowdin
- New translations from Crowdin
- New translations from Crowdin
- New translations from Crowdin
- feat: Original content updates
- New translations from Crowdin
- New translations from Crowdin
- ....

So probably let's ignore previous commits?

**Comment by alexandrtovmach** [comment]
@nodejs/i18n @nodejs/i18n-api ping

**Comment by alexandrtovmach** [comment]
This PR contains test fixes, that's blocking me from adding v14. Probably I'll add it here too

**Comment by alexandrtovmach** [comment]
@nschonni Could you review again?

**Comment by alexandrtovmach** [comment]
@nschonni please)

**Comment by nschonni** [comment]
@alexandrtovmach I'm not in favour of adding in all this content when there is no strategy for it to be consumed by anything or return the previously translated content that had translations before it was removed from the tree.
I'll dismiss my blocking review so you you can do what you want

**Comment by alexandrtovmach** [comment]
@nschonni Thank you 👍 It will be great if you can join our weekly meeting to discuss with everyone, and make some decision about it

**Comment by alexandrtovmach** [comment]
@zeke @obensource Would you suggest something?)

**Comment by alexandrtovmach** [comment]
@zeke @obensource please take a look. We need one more review

**Comment by zeke** [comment]
@amorist to the rescue! 💛

**Pull request merged**
