### PR TITLE
Add Antoine

### PR DESCRIPTION
**Pull request by Toinane**
see #15  :D Thanks!

### CODE REVIEW

**Comment by obensource** [comment]
@Toinane sound great, thanks for the PR! 🎉

**Comment by obensource** [comment]
@Toinane fyi, @bnb will also be adding you to [our team](https://github.com/orgs/nodejs/teams/i18n) asap. :)

**Comment by bnb** [comment]
Done 💥

**Comment by zeke** [comment]
👋@Toinane is an electron i18n pioneer! Happy to see you here.

**Pull request merged**
