### PR TITLE
Tweak GHA config

### PR DESCRIPTION
**Pull request by JohnTitor**
- use Node.js v14 as the active LTS is now v14
- use actions/setup-node's built-in cache feature to shrink our GHA config, see https://github.com/actions/setup-node/releases/tag/v2.2.0 for details

### CODE REVIEW

**Comment by MaledongGit** [comment]
@JohnTitor：Nothing but just a tip——It seems you've closed your copied repository's authority and not allow us to execute Mergeing.....So please open it first so as to let the manager merge your changes when your code is reviewed.

image

image

**Comment by JohnTitor** [comment]
Hmm, I can update the branch though?
image

**Review by MaledongGit — APPROVED** [review]
It looks fine with me after taking a look at your link and according to https://github.com/actions/setup-node/pull/272..But to be honest and safe, maybe you can wait for some days and get another confimation by @nodejs/actions to see the configs.
Finally I gave you an OK.

**Review by alexandrtovmach — APPROVED** [review]
LGTM! :+1:

**Pull request merged**
