### PR TITLE
fix and improve: download in parallel, change sync to async and colorize the terminal words

### PR DESCRIPTION
**Pull request by MaledongGit**
1. 'fs.remove(docDir)' is an async function, if this is called directly
and we cannot decide when to execute, and we must execute it first, so
add "await".

2. Change 'readdirSync' to 'await readdir' for the async func.

3. Use Promise.All by wraping all the download versions into a group
and then download them in parallel to improve the speed instead of
downloading one by one.

4. Make them beautiful in colors, because it's easy for the terminals
to see which is right/wrong by green/red...ect：

For Download:
Download

For Successfully Download:
Succ

For Error Download:
Err

### CODE REVIEW

**Comment by MaledongGit** [comment]
@alexandrtovmach : It seems this file has been modified by you many times, here's my first contribution, would you mind taking a period to reiew it? 

Many thanks first ;)

**Comment by alexandrtovmach** [comment]
@MaledongGit It looks like a good improvement :+1:. I don't remember if there were any problems with parallel processing, but from first view looks fine.

Thanks for contributions :muscle:

**Review by alexandrtovmach — APPROVED** [review]

**Comment by MaledongGit** [comment]
> @MaledongGit It looks like a good improvement 👍. I don't remember if there were any problems with parallel processing, but from first view looks fine.
> 
> Thanks for contributions 💪

Thank you too. I tested several times and do this submit, in my Windows 10 everything goes fine ;)

**Comment by MaledongGit** [comment]
> @MaledongGit It looks like a good improvement 👍. I don't remember if there were any problems with parallel processing, but from first view looks fine.
> 
> Thanks for contributions 💪

Thank you too. I tested several times and do this submit, in my Windows 10 everything goes fine ;)

**Comment by alexandrtovmach** [comment]
double kill :laughing: 
image

**Pull request merged**
