### PR TITLE
Add new member Franz De Copenhague

### PR DESCRIPTION
**Pull request by obensource**
Adding @FranzDeCopenhague! Stoked to have him with us! 🎉

### CODE REVIEW

**Comment by obensource** [comment]
@franzdecopenhague, would you mind verifying that we're linking to your correct twitter profile?

**Comment by RichardLitt** [comment]
Welcome, @FranzDeCopenhague!

**Comment by FranzDeCopenhague** [comment]
@obensource, OMG forgets twitter, don't have any account. That account is very politicized. Also, could be worst if keep digging looking for other franzdecopenhague twitter accounts.

**Comment by FranzDeCopenhague** [comment]
Thank you for the welcome.
Recently, I have started contributing to Electron and I am willing to help here too.
I have a software engineering background in technical documentation, translation, and internationalization, which I did mostly in Europe before moving to the US

**Comment by FranzDeCopenhague** [comment]
Well, I have created a twitter account @FranzDeCopenhag

**Comment by RichardLitt** [comment]
You don't need to have a Twitter account, at all. :) Maybe just don't include one?

**Comment by zeke** [comment]
Maybe we should turn this list into a table with a GitHub column and a Twitter column, both optional.

**Comment by RichardLitt** [comment]
@zeke Sounds like a good idea, to me.

**Comment by amor520** [comment]
#47 @zeke @RichardLitt

**Comment by RichardLitt** [comment]
We've now added the GitHub double column, so you shouldn't feel as awkward with Twitter anymore! @FranzDeCopenhague Would you prefer to only have your GitHub handle?

**Comment by FranzDeCopenhague** [comment]
Now I have a twitter account, let's use it. 
https://twitter.com/FranzDeCopenhag

https://github.com/FranzDeCopenhague

**Comment by obensource** [comment]
@FranzDeCopenhague @RichardLitt should be gtg now. 👍

**Comment by RichardLitt** [comment]
\m/

**Pull request merged**
