### PR TITLE
Add Vanessa Yuen as i18n member

### PR DESCRIPTION
**Pull request by obensource**
@vanessayuenn is awesome! 

She recently joined us in our discussion on Monday with Crowdin, and cares a ton about creating better developer experiences for non English speakers. I'm super excited to have her with us! 🎉🎉🎉

### CODE REVIEW

**Comment by lukaszewczak** [comment]
Hi @obensource , it is great to have @vanessayuenn . Maybe a stupid question :-), but can I merge this PR or this PR need to wait for something? :-)

**Comment by RichardLitt** [comment]
This needed a rebase so I merged it manually and pushed in 5a9466fd92c8150af3d046019895d6898948c7c8. Thank you, @obensource! Welcome, @vanessayuenn!

**Comment by obensource** [comment]
@RichardLitt thanks a bunch for taking care of PRs as they come in! Really appreciate it! 🙌

@lukaszewczak even though the PR is tiny, the reason why I waited was because I'd like to set the precedent in our team for having at least one review or more before anything is merged. We could easily develop a a bad team-wide habit of just pushing things through without review when they're small, it in long run it pays off to make sure everything is reviewed.

Also to note, if the PR is something more than a small addition to a .md file (like our README) we should wait to merge it (for up to 48 or 72 hours, depending) in order to ensure it's had time for discussion and at least 2 people we're able to look over it. 👍

**Comment by lukaszewczak** [comment]
Thanks for the clarification @obensource

**Comment by zeke** [comment]
> I'd like to set the precedent in our team for having at least one review or more before anything is merged. 

Should we just enforce this using branch protection?

**Comment by obensource** [comment]
DOH! Right, we should just use branch protection. Good call @zeke! 👍

**Pull request closed without merging**
