### PR TITLE
feat: test for translated files deleted in en-US

### PR DESCRIPTION
**Pull request by nschonni**
Added the test, then ran it manually against each individual version by changing the `majors` value to a single value array to then run wildcard git deletes like `git rm -rf content/v10.x/*/doc/api/all.md` for any hits

### CODE REVIEW

**Comment by nschonni** [comment]
Probably setting the flag like on the .org site so content doesn't get pre-translated as an english placeholder might help too

**Comment by alexandrtovmach** [comment]
Looks great, I'm also working on this stuff here #297 and it seems like we implemented the same functionality 😢

**Comment by alexandrtovmach** [comment]
> Probably setting the flag like on the .org site so content doesn't get pre-translated as an english placeholder might help too

Yep, I'm working on it, and also talking with Crowdin team about this https://github.com/nodejs/i18n/issues/101#issuecomment-613310389

**Comment by alexandrtovmach** [comment]
I'm really apologies for this conflict, I've mentioned my changes in related issue and didn't know that somebody work on that. Probably we need to think about some planning?

I'd propose to use next PRs instead of this one to not mix the changes and to have more functionality:
- feat: Removed mismatch content #304
- feat: Refactored tests; Added test for translated content structure #297

@nschonni I really appreciate your contributions, and want say **BIG THANKS** for your passion! At the last few days we're had issues with declining your contributions, and I want to notice that's just coincidences and nothing personal. I'm really sorry for that 😭 and I hope we'll avoid this in a future 🤗🤗🤗

**Comment by zeke** [comment]
Since #304 and #297 have landed, I think the functionality implemented here is already covered. Should this be closed?

**Comment by alexandrtovmach** [comment]
@nschonni My apologies for this, but seems like we should close PR without merge 😞
Again, we really appreciate your passion and would happy to see (and merge 😄) your contributions in next time.

**Pull request closed without merging**
