### PR TITLE
feat: Sync latest version content

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by nschonni** [comment]
@alexandrtovmach not sure where the extra stuff is coming from compared to #221

**Comment by alexandrtovmach** [comment]
@nschonni not sure why it's happen, but let's postpone this PR for a bit. I'm turned on the sync process, and don't want to restart it again

**Comment by nschonni** [comment]
No worries, I saw the 100+ emails before i muted that PR :)

**Comment by alexandrtovmach** [comment]
It seems like sync completed, so we can merge it

**Pull request merged**
